### ISSUE TITLE
IE11 not working

### ISSUE THREAD

**Issue by Shinigami92** [joffrey-bion/livedoc#121]
**Is your feature request related to a problem? Please describe.**
We have a Windows Terminal Server and some of our managers want to use IE (v11)
I don't know why, because I think there are better ways to destroy oneself, but ...

**Describe the solution you'd like**
Can you show a banner that says that IE is not supported and may list supported browsers XD

**Describe alternatives you've considered**
Use polyfills to support IE
eg: core-js or babel-polyfill

**Additional context**
IE ... will die in 2025

**Comment by joffrey-bion** [comment]
Hi! Thanks for opening an issue, I had not given a thought about IE since I believed this kind of docs was intended to developers, and which sane developer would use IE? :)

I understand that at least a warning notice should be present, rather than the application crashing. It should not be too hard to include the necessary polyfills, the hardest part being accepting to install IE 11 at home to test. 
Pull-requests are welcome if you'd like to make one, though!

**Comment by Shinigami92** [comment]
Unfortunately, I only master Angular and Vue
I don't know exactly how React works, so I think you've implemented that much faster yourself

Otherwise, I would like to help with other problems, of course

**Comment by joffrey-bion** [comment]
I perfectly understand. I'll try to take care of this ASAP, but I believe this is not the highest priority issue.

As a side note, any reason they don't use Edge?

**Comment by Shinigami92** [comment]
The Terminal Server is Windows Server 2012
