### ISSUE TITLE
[Minor] Empty sources and javadocs artifacts for ui-webjars

### ISSUE THREAD

**Issue by ST-DDT** [joffrey-bion/livedoc#86]
Just a minor note, the sources and javadocs jars for livedoc-ui-webjar are empty.

Theoretically you could avoid uploading them to reduce the total number of artifacts.
Or at least you could add the actual sources to the sources.jar

Downloading a few more bytes does not hurt, so you might as well ignore/close this.

**Comment by joffrey-bion** [comment]
Again thanks for your feedback, it's nice to see that some people care about doing things right.

Unfortunately, the Javadoc and sources artifacts [are a requirement for Maven central](http://central.sonatype.org/pages/requirements.html), so I have to upload them, even if empty AFAIU :(

That being said, I didn't realize the webjar didn't contain the sources. This is because artifact upload is configured generically for all subprojects, which are all Java except this one, which is kinda special because it only contains frontend static files.

To be honest, it doesn't add up much weight to add the javascript/HTML sources to the sources artifact (I think ~600KB), but I don't think IDEs have any kind of support for this kind of sources jar, as opposed to real Java library sources jars. So I'm afraid it will be of no use to anyone. think I'll just leave it as is for now.
